name: ndarville
description: "Breaking it down"

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0

gems:
    - jekyll-redirect-from
