name: ndarville
description: "Composing frozen music for the web"
url: http://ndarville.github.io
assets: http://ndarville.github.io/assets/
repo: https://github.com/ndarville/ndarville.github.io/

markdown: kramdown
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0
