name: ndarville
description: "Breaking it down"
url: https://ndarville.github.io
enforce_ssl: ndarville.github.io

author:
    - N. Darville

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

include: ['.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

prose:
    siteurl: 'https://ndarville.github.io'
    metadata:
        _drafts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: categories
              field:
                  element: hidden
                  value: blog
            - name: title
              field:
                  element: text
                  value: ""
            - name: date
              field:
                  element: hidden
                  value: ""
            - name: excerpt
              field:
                  element: text
                  value: ""
                  placeholder: Use 200 characters at most.
            - name: id
              field:
                  element: hidden
                  value: ""
            - name: tags
              field:
                  element: hidden
                  value: ""
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: title
              field:
                  element: text
                  value: ""
                  label: Title
            - name: date
              field:
                  element: text
                  value: ""
                  label: Date
                  placeholder: YYYY-MM-DD HH:MM:SS
                  help: Uses 24-hour notation
            - name: excerpt
              field:
                  element: text
                  value: ""
                  label: Excerpt/Description
                  placeholder: Use 200 characters at most.
            - name: slug
              field:
                  element: text
                  value: ""
                  label: Slug
            - name: id
              field:
                  element: number
                  value: ""
                  label: ID
            - name: tags
              field:
                  element: multiselect
                  label: Tags
                  options:
                      - name: Tutorials
                        value: tutorials
                  alterable: true
            - name: categories
              field:
                  element: hidden
                  value: blog
                  label: Categories

    ignore:
        - .gitignore
        - .htaccess
        - _config.yml
        - favicon.ico
        - feed.atom
        - Gemfile
        - Gemfile.lock
        - identicon.png
        - README.md
        - robots.txt
        - 404.html
        - index.html
        - /_layouts
        - /_includes
        - /_site
        - /assets
        - /css
        - /js
        - /links
