name: ndarville
description: "Composing frozen music for the web"
url: http://ndarville.github.io
repo: https://github.com/ndarville/ndarville.github.io

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0
