name: ndarville
description: "Composing frozen music for the web"
url: http://ndarville.github.io
repo: https://github.com/ndarville/ndarville.github.io/

markdown: redcarpet
redcarpet:
    extensions: ["smart", "footnotes"]
pygments: true

limit_posts: 0
