name: ndarville
description: "Breaking it down"
url: http://ndarville.github.io

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0
