name: ndarville
description: "Breaking it down"
url: https://ndarville.github.io
enforce_ssl: ndarville.github.io

author:
    - N. Darville

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

include: ['.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

prose:
    # rooturl: '_posts'
    siteurl: 'https://ndarville.github.io'
    # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
    # media: '/assets/'
    ignore:
        - .gitignore
        - .htaccess
        - _config.yml
        - favicon.ico
        - feed.atom
        - Gemfile
        - Gemfile.lock
        - identicon.png
        - README.md
        - robots.txt
        - 404.html
        - index.html
        - /_layouts
        - /_includes
        - /_site
        - /assets
        - /css
        - /js
        - /links
