name: ndarville
description: "Breaking it down"
url: https://ndarville.github.io
enforce_ssl: ndarville.github.io

markdown: kramdown
kramdown:
    input: GFM
    coderay_line_numbers: ''
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
pygments: true

limit_posts: 0

gems:
    - jekyll-redirect-from

include: ['.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
